# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/adamj/Desktop/Vitis/Lab6/hdmi_text_controller/hdmi_text_controller.srcs/sources_1/bd/hdmi_text_controller/ip/hdmi_text_controller_clk_wiz_1_2/hdmi_text_controller_clk_wiz_1_2.xci
# IP: The module: 'hdmi_text_controller_clk_wiz_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/adamj/Desktop/Vitis/Lab6/hdmi_text_controller/hdmi_text_controller.gen/sources_1/bd/hdmi_text_controller/ip/hdmi_text_controller_clk_wiz_1_2/hdmi_text_controller_clk_wiz_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_text_controller_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/adamj/Desktop/Vitis/Lab6/hdmi_text_controller/hdmi_text_controller.gen/sources_1/bd/hdmi_text_controller/ip/hdmi_text_controller_clk_wiz_1_2/hdmi_text_controller_clk_wiz_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_text_controller_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/adamj/Desktop/Vitis/Lab6/hdmi_text_controller/hdmi_text_controller.gen/sources_1/bd/hdmi_text_controller/ip/hdmi_text_controller_clk_wiz_1_2/hdmi_text_controller_clk_wiz_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_text_controller_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/adamj/Desktop/Vitis/Lab6/hdmi_text_controller/hdmi_text_controller.srcs/sources_1/bd/hdmi_text_controller/ip/hdmi_text_controller_clk_wiz_1_2/hdmi_text_controller_clk_wiz_1_2.xci
# IP: The module: 'hdmi_text_controller_clk_wiz_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/adamj/Desktop/Vitis/Lab6/hdmi_text_controller/hdmi_text_controller.gen/sources_1/bd/hdmi_text_controller/ip/hdmi_text_controller_clk_wiz_1_2/hdmi_text_controller_clk_wiz_1_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_text_controller_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/adamj/Desktop/Vitis/Lab6/hdmi_text_controller/hdmi_text_controller.gen/sources_1/bd/hdmi_text_controller/ip/hdmi_text_controller_clk_wiz_1_2/hdmi_text_controller_clk_wiz_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_text_controller_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/adamj/Desktop/Vitis/Lab6/hdmi_text_controller/hdmi_text_controller.gen/sources_1/bd/hdmi_text_controller/ip/hdmi_text_controller_clk_wiz_1_2/hdmi_text_controller_clk_wiz_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_text_controller_clk_wiz_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
