# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hdmi_text_controller/hdmi_text_controller.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller || ORIG_REF_NAME==hdmi_text_controller} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_microblaze_0_0/hdmi_text_controller_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_microblaze_0_0 || ORIG_REF_NAME==hdmi_text_controller_microblaze_0_0} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_dlmb_v10_0/hdmi_text_controller_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_dlmb_v10_0 || ORIG_REF_NAME==hdmi_text_controller_dlmb_v10_0} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_ilmb_v10_0/hdmi_text_controller_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_ilmb_v10_0 || ORIG_REF_NAME==hdmi_text_controller_ilmb_v10_0} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_dlmb_bram_if_cntlr_0/hdmi_text_controller_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==hdmi_text_controller_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_ilmb_bram_if_cntlr_0/hdmi_text_controller_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==hdmi_text_controller_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_lmb_bram_0/hdmi_text_controller_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_lmb_bram_0 || ORIG_REF_NAME==hdmi_text_controller_lmb_bram_0} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_xbar_0/hdmi_text_controller_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_xbar_0 || ORIG_REF_NAME==hdmi_text_controller_xbar_0} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_microblaze_0_axi_periph_0/hdmi_text_controller_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_microblaze_0_axi_periph_0 || ORIG_REF_NAME==hdmi_text_controller_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_microblaze_0_axi_intc_0/hdmi_text_controller_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_microblaze_0_axi_intc_0 || ORIG_REF_NAME==hdmi_text_controller_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_mdm_1_0/hdmi_text_controller_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_mdm_1_0 || ORIG_REF_NAME==hdmi_text_controller_mdm_1_0} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_clk_wiz_1_0/hdmi_text_controller_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_clk_wiz_1_0 || ORIG_REF_NAME==hdmi_text_controller_clk_wiz_1_0} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_rst_clk_wiz_1_100M_0/hdmi_text_controller_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==hdmi_text_controller_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_axi_uartlite_0_0/hdmi_text_controller_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_axi_uartlite_0_0 || ORIG_REF_NAME==hdmi_text_controller_axi_uartlite_0_0} -quiet] -quiet

# XDC: c:/Users/adamj/Desktop/Vitis/Lab6/hdmi_text_controller_2/hdmi_text_controller_2.gen/sources_1/bd/hdmi_text_controller/hdmi_text_controller_ooc.xdc
