# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/hdmi_text_controller/hdmi_text_controller.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller || ORIG_REF_NAME==hdmi_text_controller} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_microblaze_0_3/hdmi_text_controller_microblaze_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_microblaze_0_3 || ORIG_REF_NAME==hdmi_text_controller_microblaze_0_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_dlmb_v10_3/hdmi_text_controller_dlmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_dlmb_v10_3 || ORIG_REF_NAME==hdmi_text_controller_dlmb_v10_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_ilmb_v10_3/hdmi_text_controller_ilmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_ilmb_v10_3 || ORIG_REF_NAME==hdmi_text_controller_ilmb_v10_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_dlmb_bram_if_cntlr_3/hdmi_text_controller_dlmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==hdmi_text_controller_dlmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_ilmb_bram_if_cntlr_3/hdmi_text_controller_ilmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==hdmi_text_controller_ilmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_lmb_bram_3/hdmi_text_controller_lmb_bram_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_lmb_bram_3 || ORIG_REF_NAME==hdmi_text_controller_lmb_bram_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_xbar_3/hdmi_text_controller_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_xbar_3 || ORIG_REF_NAME==hdmi_text_controller_xbar_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_microblaze_0_axi_periph_3/hdmi_text_controller_microblaze_0_axi_periph_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_microblaze_0_axi_periph_3 || ORIG_REF_NAME==hdmi_text_controller_microblaze_0_axi_periph_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_microblaze_0_axi_intc_3/hdmi_text_controller_microblaze_0_axi_intc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_microblaze_0_axi_intc_3 || ORIG_REF_NAME==hdmi_text_controller_microblaze_0_axi_intc_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_mdm_1_3/hdmi_text_controller_mdm_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_mdm_1_3 || ORIG_REF_NAME==hdmi_text_controller_mdm_1_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_clk_wiz_1_3/hdmi_text_controller_clk_wiz_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_clk_wiz_1_3 || ORIG_REF_NAME==hdmi_text_controller_clk_wiz_1_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_rst_clk_wiz_1_100M_3/hdmi_text_controller_rst_clk_wiz_1_100M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_rst_clk_wiz_1_100M_3 || ORIG_REF_NAME==hdmi_text_controller_rst_clk_wiz_1_100M_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_axi_uartlite_0_3/hdmi_text_controller_axi_uartlite_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_axi_uartlite_0_3 || ORIG_REF_NAME==hdmi_text_controller_axi_uartlite_0_3} -quiet] -quiet

# IP: bd/hdmi_text_controller/ip/hdmi_text_controller_hdmi_text_controller_0_0/hdmi_text_controller_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_text_controller_hdmi_text_controller_0_0 || ORIG_REF_NAME==hdmi_text_controller_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: c:/Users/adamj/Desktop/Vitis/Lab6/hdmi_text_controller/hdmi_text_controller.gen/sources_1/bd/hdmi_text_controller/hdmi_text_controller_ooc.xdc
